### ISSUE TITLE
doesn't install using go 1.1.2

### ISSUE THREAD

**Issue by rogpeppe** [go-qml/qml#1]
It should probably be documented that the build
fails against go 1.1.2 with this error message:

% go get github.com/niemeyer/qml
package github.com/niemeyer/qml
    imports github.com/niemeyer/qml
    imports github.com/niemeyer/qml: /home/rog/src/go/src/github.com/niemeyer/qml/bridge.go: invalid #cgo verb: #cgo CPPFLAGS: -I/usr/include/qt5/QtCore/5.0.2/QtCore -I./cpp

**Comment by munknex** [comment]
From README:

> Go 1.2 (in development), for the C++ support of go build
