### ISSUE TITLE
Windows7 QML display a blank

### ISSUE THREAD

**Issue by afocus** [go-qml/qml#104]
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glUniformMatrix4fv'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glUniformMatrix4fvARB'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glVertexAttribPointer'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glVertexAttribPointerARB'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glVertexAttribPointer'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glVertexAttribPointerARB'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glDisableVertexAttribArray'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glDisableVertexAttribArrayARB'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glDisableVertexAttribArray'
2014/09/20 00:09:25 qwindowsglcontext.cpp:1108: getProcAddress: Unable to resolve 'glDisableVertexAttribArrayARB'

**Comment by niemeyer** [comment]
These logged messages were reported before, but they did not prevent the code from working, and this upstream bug report also points out that the underlying code worked:

https://bugreports.qt-project.org/browse/QTBUG-33454

Can you please try running one of the painting examples?

**Comment by niemeyer** [comment]
Closing for lack of details.
