### ISSUE TITLE
Embedded QML?

### ISSUE THREAD

**Issue by averrin** [go-qml/qml#122]
Hello.
Can i embed qml file to build me script into one binary file?

**Comment by janimo** [comment]
http://blog.labix.org/2014/09/26/packing-resources-into-go-qml-binaries

**Comment by niemeyer** [comment]
Right, and you can also just use a string in your Go file and load it with Engine.LoadString.

**Comment by ghost** [comment]
blog.labix.org seems to be down.
Webcache: http://webcache.googleusercontent.com/search?q=cache:http://blog.labix.org/2014/09/26/packing-resources-into-go-qml-binaries

A link to the godoc: http://godoc.org/gopkg.in/qml.v1#ResourcesPacker
