### ISSUE TITLE
Module "QtQuick" version 2.2 is not installed

### ISSUE THREAD

**Issue by tinycedar** [go-qml/qml#129]
Since I've set up the required environment in Windows 8.1 for development, I build the "basiclayouts" in example and with basiclayouts.exe built successfully.But after I ran the exe file, a error message "Module "QtQuick" version 2.2 is not installed" occurs. Could you please help solve this issue ?

![error](https://cloud.githubusercontent.com/assets/8019222/5227227/5c291e08-7733-11e4-9087-60a9e0a3cf77.png)

**Comment by niemeyer** [comment]
This would generally mean either that you're attempting to use the wrong version of QtQuick for the version of Qt and QML you have installed. Try with 2.0 or 2.1, for example.

**Comment by tinycedar** [comment]
Sorry, How to change QtQuick version ?

**Comment by niemeyer** [comment]
You change the QtQuick version by changing your version of Qt/QML, but that's not what I'm suggesting. I'm suggesting you fix the code to refer to the right version of QtQuick (and thus Qt/QML) you have installed. I cannot tell you what that one is, though, or whether it will work with the code you have at hand (it might depend on features from QtQuick 2.2).
