### ISSUE TITLE
Fullscreen toggle?

### ISSUE THREAD

**Issue by raichu** [go-qml/qml#14]
Is it possible with the current bindings?

**Comment by niemeyer** [comment]
Digging through the documentation we can see that QWindow has a "showFullScreen" slot:

```
http://qt-project.org/doc/qt-5.0/qtgui/qwindow.html
```

This may easily be called from Go with:

```
window.Call("showFullScreen")
```

**Comment by raff** [comment]
This doesn't seem to work (but I have read of similar issues in Qt, so it may not be GoQML fault).

For what is worth, this works (use this instead of window.Show()):
  window.Call("showMaximized")
