### ISSUE TITLE
Vertical resize of example window is jerky

### ISSUE THREAD

**Issue by chrisbainbridge** [go-qml/qml#148]
```
cd examples/controls/basiclayouts/basiclayouts.go
go run basiclayouts.go
```

Now resize the vertical height of the window by dragging the bottom-right corner up/down. The window contents will flicker and jerk as they are redrawn in the wrong positions. The same thing happens on other examples.

Using Intel GPU with xorg TearFree so tearing is not the problem. 

This could be a problem with the example source itself, or a problem with QT/QML on Debian Jessie.

**Comment by niemeyer** [comment]
Please report this upstream into Qt itself. The Go logic isn't doing anything besides just loading the QML file there.
