### ISSUE TITLE
Windows Deploy gives _ZN7QString13toUtf8_helperERKS_ with QT5.2.1

### ISSUE THREAD

**Issue by josephyzhou** [go-qml/qml#150]
I'm currently using QT 5.2.1 because I want to utilize QTQuick 2.2 and Controls 1.1
The app builds and `go install` with no problem. Then I did `windeployqt --force`, it grabbed all the .dll

When I tried to execute the .exe from command prompt, I'm getting this error:
`The procedure entry point _ZN7QString13toUtf8_helperERKS_ could not be located in dynamic link library`

I found this on stackoverflow, not sure if it's the same issue: http://stackoverflow.com/questions/27714446/undefined-symbol-zn7qstring13toutf8-helpererks-at-runtime

**Comment by neclepsio** [comment]
I solved using qt-x64. But to be able to run under windows, use my fork
github.com/neclepsio/qml
Il 16/mar/2015 12:04 PM "Joe Zhou" <notifications@github.com> ha scritto:
