### ISSUE TITLE
Cannot "go get" on Debian Unstable

### ISSUE THREAD

**Issue by russel** [go-qml/qml#16]
Debian Unstable purports to have a full Qt5 package set now. I installed qtbase5-private-dev and qtdeclarative5-private-dev along with everything else Qt5 and PyQt5 related that seems to be relevant, assuming the Debian dependencies will take care of everything. Sadly this appears to be not true, as I get:

> |> go get github.com/niemeyer/qml
> # github.com/niemeyer/qml
> 
> In file included from ../../github.com/niemeyer/qml/cpp/capi.cpp:9:0,
>                 from ../../github.com/niemeyer/qml/all.cpp:2:
> ../../github.com/niemeyer/qml/cpp/govalue.h:7:35: fatal error: private/qmetaobject_p.h: No such file or directory
>  #include <private/qmetaobject_p.h>
>                                    ^
> compilation terminated.

**Comment by niemeyer** [comment]
The issue is likely that Debian is using a different version of Qt which must be considered in the inclusion paths.

What version of these packages do you have?

**Comment by russel** [comment]
Looks to be 5.1.1.

**Comment by niemeyer** [comment]
If it is 5.1.1, it should be working. Can you please paste the output of these two commands:

```
dpkg -l qtbase5-private-dev
dpkg -L qtbase5-private-dev
```

**Comment by russel** [comment]
https://gist.github.com/niemeyer/7103254 (moved inline output to gist)

**Comment by niemeyer** [comment]
Please let me know whether that works.

**Comment by russel** [comment]
It seems to have installed using the Google compiler suite, however with gccgo there are a large number of compile errors. I'll post a new issue.
