### ISSUE TITLE
needs launchpad.net/gocheck

### ISSUE THREAD

**Issue by janimo** [go-qml/qml#2]
The install doc should mention it needs gocheck for running the tests, even though that can be inferred from the error message
all_test.go:8:2: cannot find package "launchpad.net/gocheck" in any of:

**Comment by niemeyer** [comment]
The install document is currently covering non-obvious dependencies that are necessary for using the package at all. I'd prefer to not mix dependencies that are needed only for running the test suite, even more considering the error message is offering such a descriptive guidance on what to do.
