### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by kylewolfe** [go-qml/qml#20]
go get github.com/niemeyer/qml
can't load package: package github.com/niemeyer/qml: /home/kyle/go/bin/src/github.com/niemeyer/qml/bridge.go: invalid #cgo verb: #cgo CPPFLAGS: -I./cpp -I/usr/include/qt5/QtCore/5.0.2/QtCore -I/usr/include/qt5/QtCore/5.1.1/QtCore -I/usr/include/qt/QtCore/5.1.1/QtCore

**Comment by kylewolfe** [comment]
Not an issue relating to go-qml

**Comment by niemeyer** [comment]
For the record, this is a symptom of using Go < 1.2.
