### ISSUE TITLE
.On() signals not working on MacOS

### ISSUE THREAD

**Issue by tmc** [go-qml/qml#24]
The signals used in the snapweb and qmlscene examples that use On() appear to not get invoked on MacOS (Qt 5.2.0, MacOS 10.9)

**Comment by niemeyer** [comment]
What release of Qt 5.2.0 is it running with?  Any error messages?

I can confirm that both of these examples are working fine on an Ubuntu Linux with Qt 5.2.0 beta1.

**Comment by tmc** [comment]
A build of the stable branch about a week ago. Building a new one now. No errors that I could get to show up but I'm not familiar with any debugging flags/env vars for qt or anything like that.

**Comment by niemeyer** [comment]
Make sure you are running the latest code of the qml package too. As mentioned in the list, a minor fix was necessary, and was pushed yesterday before this issue was opened.

**Comment by tmc** [comment]
I am and was running current HEAD. No behavior change with the new build.

**Comment by niemeyer** [comment]
Okay, thanks for checking. I'll investigate the behavior on 5.2 more carefully.

**Comment by tmc** [comment]
As of 5.2.0 this appears to be fixed!
