### ISSUE TITLE
Loading QPixmap as images?

### ISSUE THREAD

**Issue by raichu** [go-qml/qml#4]
This is more like a question: Is it possible to load a QPixmap (using loadFromData) from Go side as an image yo be used as an Image in QML?
I believe with C++ [one needs to use QDeclarativeImageProvider](http://kunalmaemo.blogspot.jp/2011/12/using-qdeclarativeimageprovider-to-load.html) (at least with Qt 4, not sure about Qt 5.1+).

An example [image viewer](http://qt-project.org/doc/qt-5.1/qtwidgets/widgets-imageviewer.html) using this package would be immensely helpful :)

**Comment by niemeyer** [comment]
That's a nice idea, thanks. We've already got the magic for moving images from Qt to Go, so moving in the other direction won't be difficult.

I'll try to have a look at the details this week. Will keep this issue open to track the support for doing this.

**Comment by raichu** [comment]
Have I mentioned that you rock? :)

**Comment by ghost** [comment]
In Qt 5.1 the class is called [QQuickImageProvider](http://qt-project.org/doc/qt-5.0/qtquick/qquickimageprovider.html).

**Comment by niemeyer** [comment]
@arbaal That may well be a good path for the bridge, via a custom image provider.

**Comment by raichu** [comment]
Friendly ping :)

**Comment by niemeyer** [comment]
Thanks for the poke. I wanted to sort out the static vs. dynamic situation before diving into such bridges, and this is now done. I'll have a look at this.

**Comment by niemeyer** [comment]
Sorry, but I actually won't be able to look at this until next week when I'm back from a few days off.

**Comment by raichu** [comment]
Still sounds great :) Thanks!

**Comment by raichu** [comment]
Any updates?

**Comment by niemeyer** [comment]
I'm just back from a long work trip. My plan is to get something done before the end of the week.

Sorry for the delay on this.

**Comment by raichu** [comment]
Thanks!

Sorry about multiple pings :)

**Comment by niemeyer** [comment]
This is in progress.

**Comment by raichu** [comment]
Thanks!
