### ISSUE TITLE
Install dependencies on Ubuntu 12.04.4

### ISSUE THREAD

**Issue by bekharsky** [go-qml/qml#44]
Hi! I have failed to install ubuntu-sdk on Ubuntu 12.04.4, so:

sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
sudo apt-get update
sudo apt-get install qtdeclarative5-dev qtbase5-private-dev qtdeclarative5-private-dev libqt5opengl5-dev qtdeclarative5-qtquick2-plugin 

After that Go QML compiles succesfully and all of the examples too. For Go installation I use GVM.

**Comment by oblitum** [comment]
@Alinaki have you tried to grab raw Qt? I just use Qt compiled from sources on Ubuntu 13.10, it works.

**Comment by bekharsky** [comment]
@oblitum Sorry, I just update my comment. Now it is a manual for 12.04 :)

**Comment by oblitum** [comment]
@Alinaki ah ok.
