### ISSUE TITLE
QVariantMap Support

### ISSUE THREAD

**Issue by saward** [go-qml/qml#47]
I tried to pass an object to a Go function like follows:
game.createJob("walkto", false, {"x": tx, "y": ty})

However, the Go code fails to understand the passed object:
panic: unsupported variant type: 8 (QVariantMap)

Posting issue here as per request.  If I get around to implementing it myself, I'll post the code up.  However, I think it is unlikely.  I'll probably try to press forward working on my application.

**Comment by niemeyer** [comment]
This was just fixed by fda6e9c.
