### ISSUE TITLE
Problem with native appearance

### ISSUE THREAD

**Issue by sshikaree** [go-qml/qml#50]
Hi! I've got a problem in Ubuntu 13.10. When i preview UI with `qmlscene` it looks fine - 
![2014-03-16 22 27 55](https://f.cloud.github.com/assets/3266489/2431653/2bfa0c36-ad3c-11e3-9ccf-abd88ab51b53.png)
But when i build application with **_go-qml_** it looks strange - 
![2014-03-16 22 30 39](https://f.cloud.github.com/assets/3266489/2431660/76372cca-ad3c-11e3-835f-926230f44511.png)

**Comment by Druage** [comment]
Are you using QGuiApplication instead of QApplication? Look here http://qt-project.org/doc/qt-5/qtquickcontrols-overview.html I was having the same problem.

**Comment by sshikaree** [comment]
Hmm.. But I don't touch C++ at all. Just opening qml file with Go application.

**Comment by Druage** [comment]
Is this just a QML file without any backend golang code? If you post the results of your main function, I could solve this for ya.

**Comment by sshikaree** [comment]
**Druage**, thanks for helping! Here is simplified example - https://gist.github.com/sshikaree/536cb210c4be4aceead4 . And how it looks in QtCreator: 
![2014-03-19 08 59 58](https://f.cloud.github.com/assets/3266489/2456941/277b7788-af28-11e3-98e8-9b0625c4f4d0.png)
and built with go-qml:
![2014-03-19 08 59 08](https://f.cloud.github.com/assets/3266489/2456951/4ba9335c-af28-11e3-93b8-cdca5d746f8a.png)

**Comment by Druage** [comment]
Hmm I was reading the source code and I did not I could only find an instance in the capi where the developer uses QGuiApplication instead of QApplication in the newGuiApplication function. I'm not entirely sure, but this "could" be the issue. The developer would be able to help you more. You would need the QApplication instance because using QApplication applies widget styling.
Sorry I couldn't fix the issue for you.

**Comment by niemeyer** [comment]
Thanks a lot for your help, @Druage. You've probably nailed down the issue. I'll see if using QApplication there solves the problem.

**Comment by niemeyer** [comment]
It does solve the problem. Thanks for the report @sshikaree, and for pointing out the issue @Druage.

**Comment by Druage** [comment]
@niemeyer Glad I could be of help and keep up the great work.

**Comment by sshikaree** [comment]
Great! :-)
