### ISSUE TITLE
Unsupported framebuffer format.

### ISSUE THREAD

**Issue by neclepsio** [go-qml/qml#58]
Sometimes when running the Gopher example I get this error:

```
qopenglframebufferobject.cpp:353: QOpenGLFramebufferObject: Unsupported framebuffer format.
```

After, Paint get called, but there is no update on the screen.

Restarting the program just a few frames are drawn before the error is thrown. At that point, only restarting graphics driver (or Windows) helps.

I'm using 64-bit Windows 7 with nVidia Quadro FX 3500, latest available driver.

**Comment by niemeyer** [comment]
Can you please try running the example with:

```
QML_NO_THREADED_RENDERER=1 ./gopher
```

**Comment by neclepsio** [comment]
The issue did not appear in my tests. Being "random", I cannot guarantee it's solved, but it seems so.

**Comment by neclepsio** [comment]
Sorry: it happens with this setting too, but it appears to be less frequent.

**Comment by niemeyer** [comment]
I'm considering this bug fixed due to the new GL APIs. Please reopen it if you see the same issue again.
