### ISSUE TITLE
error: comma at end of enumerator list [-pedantic]

### ISSUE THREAD

**Issue by wiliamsouza** [go-qml/qml#6]
On ubuntu 12.04 box.

$ go build
# github.com/niemeyer/qml

In file included from /home/wiliam/devel/gocode/src/github.com/niemeyer/qml/cpp/govalue.h:9:0,
                 from /home/wiliam/devel/gocode/src/github.com/niemeyer/qml/cpp/capi.cpp:8,
                 from /home/wiliam/devel/gocode/src/github.com/niemeyer/qml/all.cpp:2:
/home/wiliam/devel/gocode/src/github.com/niemeyer/qml/cpp/capi.h:49:20: error: comma at end of enumerator list [-pedantic]

**Comment by gatspy** [comment]
I also have to make the same mistake.

**Comment by niemeyer** [comment]
Thanks for the report. Let's see if that helps.
