### ISSUE TITLE
Tableview update

### ISSUE THREAD

**Issue by ildus** [go-qml/qml#75]
Hi, I'm trying to show a slice of objects in TableView, and i have a trouble with updating. Because model is integer (by examples), when i add object as first item in slice it updates only second item, so in result i have two equal rows in table. How can i update the whole table or specific rows? Is there a way for using slice as model?

**Comment by niemeyer** [comment]
It sounds like you are updating a single value instead of two, and providing that same value to the two rows.

Can you please send the example to the mailing list so people can help you?
