### ISSUE TITLE
sys/mman.h is not available under Windows

### ISSUE THREAD

**Issue by neclepsio** [go-qml/qml#79]
sys/mman.h, which is required by SetupTesting, is not available under Windows using mingw. 
Maybe [this project](http://code.google.com/p/mman-win32/) can help.
The header is required by testing.go in v1-dev branch.

**Comment by niemeyer** [comment]
I think we can just call the underlying VirtualProtect on Windows. It's a single call, and is very close to what we do anyway. Do you want to give it a try? Don't worry about making it nice.. if you can just hack the code to replace mprotect by VirtualProtect and see whether it works, it'd already be a good help.

You can see how the arguments map in the mman-win32 project you referenced:

https://code.google.com/p/mman-win32/source/browse/trunk/mman.c#139

**Comment by neclepsio** [comment]
This is compilation log:

In file included from ..\gopkg.in\qml.v1\all.cpp:11:0:
..\gopkg.in\qml.v1\cpp/mmemwin.cpp: In function 'int mprotect(void*, size_t, int)':
..\gopkg.in\qml.v1\cpp/mmemwin.cpp:15:11: error: 'PAGE_READ' was not declared in this scope
   wprot = PAGE_READ;

I suppose you want to use PAGE_READONLY.

**Comment by niemeyer** [comment]
Sorry for the silly mistake. I haven't had a chance to test it in a Windows machine.

Can you please try again?

**Comment by neclepsio** [comment]
It works.

**Comment by niemeyer** [comment]
\o/
