### ISSUE TITLE
OSX _Cfunc_glBlendColor crashes

### ISSUE THREAD

**Issue by morriswinkler** [go-qml/qml#83]
I installed qml.v1 and get following error on the gopher example

../../work-in-progress/gl/gengl.go:3267: cannot use C.GLclampf(red) (type C.GLclampf) as type C.GLfloat in argument to _Cfunc_glBlendColor
../../work-in-progress/gl/gengl.go:3267: cannot use C.GLclampf(green) (type C.GLclampf) as type C.GLfloat in argument to _Cfunc_glBlendColor
../../work-in-progress/gl/gengl.go:3267: cannot use C.GLclampf(blue) (type C.GLclampf) as type C.GLfloat in argument to _Cfunc_glBlendColor
../../work-in-progress/gl/gengl.go:3267: cannot use C.GLclampf(alpha) (type C.GLclampf) as type C.GLfloat in argument to _Cfunc_glBlendColor

looks like the wrong data type is passed to C.GLclampf()

**Comment by niemeyer** [comment]
The gl package is being completely rewritten to make use of GL-version-specific endpoints resolved by Qt itself. This will get fixed on the way.
