### ISSUE TITLE
Ubuntu 14 Installation Error

### ISSUE THREAD

**Issue by bitcoinsSG** [go-qml/qml#85]
when using  go get -u github.com/go-qml/qml I get the following error
# github.com/go-qml/qml

../../../go-qml/qml/error.go:4: "ERROR: the correct import path is gopkg.in/qml.v1 ... " evaluated but not used

**Comment by zoli** [comment]
Isn't the error message obvious you should use gopkg.in/qml.v1 instead of github.com/go-qml/qml
