### ISSUE TITLE
cannot convert sync (type glbase.Sync) to type _Ctype_GLsync

### ISSUE THREAD

**Issue by marguerite** [go-qml/qml#97]
Hi, 

I'm building go-qml on openSUSE 13.1, using golang 1.3 (default one).

here's what I get:

[  379s] gl/4.2core/gl.go:2330[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1126]: undefined: INFO_LOG_LENGTH
[  379s] gl/4.2core/gl.go:2396[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1146]: undefined: INFO_LOG_LENGTH
[  379s] gl/4.2core/gl.go:3813[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1885]: cannot convert sync (type glbase.Sync) to type _Ctype_GLsync
[  379s] gl/4.2core/gl.go:3823[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1897]: cannot convert sync (type glbase.Sync) to type _Ctype_GLsync
[  379s] gl/4.2core/gl.go:3828[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1903]: cannot convert sync (type glbase.Sync) to type _Ctype_GLsync
[  379s] gl/4.2core/gl.go:3834[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1910]: cannot convert sync (type glbase.Sync) to type _Ctype_GLsync
[  379s] gl/4.2core/gl.go:3839[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1916]: cannot convert sync (type glbase.Sync) to type _Ctype_GLsync
[  379s] gl/4.2core/gl.go:3846[/tmp/go-build998181402/gopkg.in/qml.v1/gl/4.2core/_obj/gl.cgo1.go:1924]: cannot convert glresult (type _Ctype_GLsync) to type glbase.Sync

I don't know golang that deep...I just need to package go-qml for limetext dependency :-)...so please tell me why I was wrong...

Thanks

Marguerite

**Comment by marguerite** [comment]
This patch compiles well:

<pre>
Index: qml/gl/glbase/glbase.go
===================================================================
--- qml.orig/gl/glbase/glbase.go
+++ qml/gl/glbase/glbase.go
@@ -1,5 +1,7 @@
 package glbase
 
+import "unsafe"
+
 // A Context represents an OpenGL context that may be rendered on by the
 // version-specific APIs under this package.
 type Context struct {
@@ -18,7 +20,7 @@ type Contexter interface {
 type (
    Bitfield uint32
    Enum     uint32
-   Sync     uintptr
+   Sync     unsafe.Pointer
    Clampf   float32
    Clampd   float64
</pre>

**Comment by niemeyer** [comment]
Sorry for the trouble. I'll address these issues shortly.

**Comment by marguerite** [comment]
@niemeyer Thanks, and this, please?

<pre>
Index: qml/gl/3.2compat/gl.go
===================================================================
--- qml.orig/gl/3.2compat/gl.go
+++ qml/gl/3.2compat/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const(
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man3/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/3.3core/gl.go
===================================================================
--- qml.orig/gl/3.3core/gl.go
+++ qml/gl/3.3core/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man3/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/4.0compat/gl.go
===================================================================
--- qml.orig/gl/4.0compat/gl.go
+++ qml/gl/4.0compat/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man4/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/4.0core/gl.go
===================================================================
--- qml.orig/gl/4.0core/gl.go
+++ qml/gl/4.0core/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man4/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/4.1compat/gl.go
===================================================================
--- qml.orig/gl/4.1compat/gl.go
+++ qml/gl/4.1compat/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man4/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/4.1core/gl.go
===================================================================
--- qml.orig/gl/4.1core/gl.go
+++ qml/gl/4.1core/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man4/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/4.2compat/gl.go
===================================================================
--- qml.orig/gl/4.2compat/gl.go
+++ qml/gl/4.2compat/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man4/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
Index: qml/gl/4.2core/gl.go
===================================================================
--- qml.orig/gl/4.2core/gl.go
+++ qml/gl/4.2core/gl.go
@@ -39,7 +39,9 @@ type GL struct {
    funcs unsafe.Pointer
 }
 
-const ()
+const (
+        INFO_LOG_LENGTH                                    = 0x8B84
+)
 
 // https://www.opengl.org/sdk/docs/man4/xhtml/glViewport.xml
 func (gl *GL) Viewport(x, y, width, height int) {
</pre>

**Comment by niemeyer** [comment]
Please try updating. Change e3d7ffdc should have fixed this.

**Comment by niemeyer** [comment]
As a side note if you decide to hack further on those packages, they are all automatically generated by the tool in gl/gengl.
